---
title: "RQ1 Multimodal ONA Model for the University of Lyon"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

# 0. Set working directory and load necessary packages 
```{r, setup, include=FALSE, echo=FALSE}
# Set local working directory
# setwd("~/Desktop/epistemic_analytics/lyon_collab")
```

```{r, setup, include=FALSE, echo=FALSE}
# knitr::opts_knit$set(root.dir = '~/Documents/GitHub/lyon_collab')
```

```{r, echo = FALSE, message = FALSE}
# Reinstallation sequence for ONA package
# remove.packages("ona")
# install.packages("ona", repos = c("https://epistemic-analytics.gitlab.io/qe-packages/ona/cran/", "https://cran.rstudio.org"))
# remove.packages("tma")
# install.packages("tma", repos = c("https://epistemic-analytics.gitlab.io/qe-packages/tma/cran/", "https://cran.rstudio.org"))

# Load necessary libraries 
library(rENA)
library(ona) 
library(tma)
library(readxl)
library(tidyverse)
library(rcompanion)
library(psych)
# Source plotter code
# source("~/Desktop/epistemic_analytics/lyon_collab/code/ona_plotter_lyon.R")
```

# 1. Read in and process dataset
```{r}
# Read in dataset, remove unnecessary columns 
df <- read.csv("~/Desktop/epistemic_analytics/lyon_collab/data/LetsPlay_TMA_1stmodel.csv") %>%
  select(-X)

# Fix line 6502 
df[6502,6] <- "gaze"
df[6502,15]<- 1
df[,15] <- as.numeric(df[,15])
```

# 2. Specify parameters: Units, codes, metadata, and HOO-rules 
```{r}
# Define units, codes, metadata, and HOO rules
unit_cols <- c("classroom", "group", "actor")
code_cols <- c("multimodal.relevance_correct..hors.pertinence.linguistique.", "multimodal.relevance_correct.and.complete", "multimodal.relevance_correct.and.incomplete", "multimodal.relevance_incorrect","verbal.relevance_correct.and.complete",            "verbal.relevance_correct.and.incomplete", "verbal.relevance_incorrect", "Intercomprehension.checks_VIC.collective", "Intercomprehension.checks_VIC.individuelle")
meta_cols <- c("qualitative_content", "Rules")
HOO_rules_model <- tma:::rules( 
  classroom %in% UNIT$classroom & group %in% UNIT$group 
)
```

# 3. Define contexts based on HOO rules
```{r}
context_model <- tma:::contexts(
  x = df,
  units = unit_cols,
  hoo_rules = HOO_rules_model
)
```

# 4. Build T/ONA model
```{r}
# Define accumulation function
ona_multimodal_tif_accum <- tma:::accumulate_contexts (
    x = context_model,
    codes = code_cols,
    weight.by = function(x) { x },
    # Define the decay function to account differently for verbal, gaze, and gesture, arbitrary values selected
    decay.function = function(x) {
      mod <- FULL_CONTEXT[RESPONSE_INDEX, ]$Modality
      if(mod == "verbal")
        return(x<(FULL_CONTEXT[ROWS]$End - FULL_CONTEXT[ROWS]$Start + 15))*1
      if(mod == "gesture")
        return(x<(FULL_CONTEXT[ROWS]$End - FULL_CONTEXT[ROWS]$Start + 10))*1
      if(mod == "gaze")
        return(x<(FULL_CONTEXT[ROWS]$End - FULL_CONTEXT[ROWS]$Start + 5))*1
      else
        return(0)
      },
    time.column = "Start", 
    return.ena.set = FALSE,
    mode.column = "Modality"
) 

# Make set 
# ona_multimodal_tif_set <- model(ona_multimodal_tif_accum)

# MR, CE2 vs. 5
my_rotation.params = 
  list(CE2 = ona_multimodal_tif_accum$meta.data$classroom == "CE2",
       `5` = ona_multimodal_tif_accum$meta.data$classroom == "5")

ona_multimodal_tif_set <-
  model(ona_multimodal_tif_accum,                                 # The previously run accumulation above
        rotate.using ="mean",                  # Function provided by ONA
        rotation.params = my_rotation.params   # The defined paremeters for rotation
        )
```

# 5. Analyze model  
## 1) Goodness of fit
```{r}
# Pearson's R
ona_multimodal_tif_gof <- ona:::correlations(ona_multimodal_tif_set)$pearson
ona_multimodal_tif_gof[[1]]
```
## 2) Variance explained
```{r}
ona_multimodal_tif_SVD <- lm(ona_multimodal_tif_set$points$MR1 ~ ona_multimodal_tif_set$points$classroom) %>% summary()
ona_multimodal_tif_SVD$r.squared
```
## 3) Interpretive Alignment
```{r}
source("~/Desktop/epistemic_analytics/lyon_collab/code/rq_ona_plotter_lyon.R")
# Plot ONA plot
make.ona.plot(ona_multimodal_tif_set, 
              "Lyon Multimodal Model") 
```


## Statistics

```{r}
data <- as.data.frame(ona_multimodal_tif_set$points$MR1) %>% 
  mutate(points = ona_multimodal_tif_set$points$MR1, classroom = ona_multimodal_tif_set$points$classroom) %>%
  select(-"ona_multimodal_tif_set$points$MR1")

# Verify assumptions of normality and homogenous variance
anova <- aov(ona_multimodal_tif_set$points$MR1 ~ ona_multimodal_tif_set$points$classroom)
anova_residuals <- residuals(object = anova)
shapiro.test(x = anova_residuals) # Fails Shapiro-Wilk test--scores not normally distributed (significant p-value)

leveneTest(points ~ classroom, data = data) # Passes Levene's test, variance is homogenous 

# Pairwise wilcox test with BH corrections, providing statistical warrant for ONA-score observation
result <- pairwise.wilcox.test(ona_multimodal_tif_set$points$MR1, ona_multimodal_tif_set$points$classroom, p.adjust.method = "BH")
result

# Effect sizes (rank-biserial correlation) for CE2 v. 5
CE2 <- data %>%
  filter(classroom == "CE2")
CE2 <- pull(CE2, points)

`5` <- data %>%
  filter(classroom == "5")
`5` <- pull(`5`, points)

abs(wilcoxonR(CE2, `5`)) # NaN?

```

